# Generated by Django 4.0.1 on 2022-02-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='restaurant',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Iranian-restaurant', 'Iranian restaurant'), ('Italian-restaurant', 'Italian restaurant'), ('French-restaurant', 'French restaurant'), ('Chinese-restaurant', 'Chinese restaurant'), ('fastfood', 'fastfood')], help_text='please choose type of restaurant', max_length=30),
        ),
    ]
