# Generated by Django 4.0.1 on 2022-02-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_food_menu_item'),
        ('restaurant', '0002_rename_restaurant_personnel_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.food'),
        ),
    ]
