# Generated by Django 4.0.1 on 2022-02-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='menu_item',
        ),
    ]
